// Auth actionTypes
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_USER = "SET_USER";

// Document actionTypes
export const SET_INCOMING_COUNT = "SET_INCOMING_COUNT";
export const SET_OUTGOING_COUNT = "SET_OUTGOING_COUNT";
export const SET_ARCHIVE_COUNT = "SET_ARCHIVE_COUNT";
export const SET_NOTIFICATIONS_COUNT = "SET_NOTIFICATIONS_COUNT";
export const SET_REQUEST_DETAILS = "SET_REQUEST_DETAILS";
export const SET_VIEW_DOCUMENT = "SET_VIEW_DOCUMENT";

// Tracking actionTypes
export const SET_OPEN_TRACKING_MODAL = "SET_OPEN_TRACKING_MODAL";
export const SET_TRACKING_DOC_ID = "SET_TRACKING_DOC_ID";
export const SET_DOCTYPE = "SET_DOCTYPE";
export const SET_ACTIVATED_DOCUMENTS_DETAILS =
  "SET_ACTIVATED_DOCUMENTS_DETAILS";

// Directories
export const SET_BREADCRUMBS = "SET_BREADCRUMBS";
export const CLEAR_BREADCRUMBS = "CLEAR_BREADCRUMBS";
export const REMOVE_BREADCRUMBS = "REMOVE_BREADCRUMBS";
export const POP_BREADCRUMBS = "POP_BREADCRUMBS";
export const OPEN_PASSWORD_MODAL = "OPEN_PASSWORD_MODAL";

// Websocket
export const NEW_INCOMING = "NEW_INCOMING";
